create table public."Requests"
(
    "Id"               integer generated by default as identity
        constraint "PK_Requests"
            primary key,
    "UserId"           integer                  not null
        constraint "FK_Requests_Users_UserId"
            references public."Users"
            on delete cascade,
    "OdFromId"         integer                  not null
        constraint "FK_Requests_Airports_OdFromId"
            references public."Airports"
            on delete cascade,
    "OdToId"           integer                  not null
        constraint "FK_Requests_Airports_OdToId"
            references public."Airports"
            on delete cascade,
    "DateFrom"         date                     not null,
    "DateTo"           date                     not null,
    "OperativeDay"     integer                  not null,
    "DestinationId"    integer                  not null
        constraint "FK_Requests_Destinations_DestinationId"
            references public."Destinations"
            on delete cascade,
    "SeasonId"         integer                  not null
        constraint "FK_Requests_Seasons_SeasonId"
            references public."Seasons"
            on delete cascade,
    "Year"             smallint                 not null,
    "CurrencyId"       integer
        constraint "FK_Requests_UnitOfMeasures_CurrencyId"
            references public."UnitOfMeasures"
            on delete cascade,
    "ContractTypeId"   integer
        constraint "FK_Requests_ContractTypes_ContractTypeId"
            references public."ContractTypes"
            on delete cascade,
    "RejectionReason"  text,
    "Status"           integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4, 5])),
    "RoutingId"        integer
        constraint "FK_Requests_Routings_RoutingId"
            references public."Routings"
            on delete cascade,
    "GuaranteedSeatsP" integer                  not null,
    "GuaranteedSeatsY" integer                  not null,
    "GuaranteedSeatsF" integer                  not null,
    "GuaranteedSeatsB" integer                  not null,
    "ReleaseSeatsP"    integer                  not null,
    "ReleaseSeatsY"    integer                  not null,
    "ReleaseSeatsF"    integer                  not null,
    "ReleaseSeatsB"    integer                  not null,
    "Frequency"        integer                  not null
        constraint "CKE_Frequency"
            check ("Frequency" = ANY (ARRAY [0, 1, 2, 3])),
    "Notes"            text,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null,
    "ProviderId"       integer
        constraint "FK_Requests_Companies_ProviderId"
            references public."Companies"
            on delete cascade
);

comment on column public."Requests"."Status" is 'EnmRequestStatus values ( Requested = 0, Rejected = 1, InProgress = 2, Quoted = 3, PartiallyConfirmed = 4, Confirmed = 5 )';

comment on column public."Requests"."Frequency" is 'EnmOriginDestinationFrequency values ( Daily = 0, Weekly = 1, DD21 = 2, Monthly = 3 )';

alter table public."Requests"
    owner to neos;

create index "IX_Requests_ContractTypeId"
    on public."Requests" ("ContractTypeId")
    where ("IsDeleted" = false);

create index "IX_Requests_IsDeleted"
    on public."Requests" ("IsDeleted")
    where ("IsDeleted" = false);

create index "IX_Requests_OdFromId"
    on public."Requests" ("OdFromId")
    where ("IsDeleted" = false);

create index "IX_Requests_OdToId"
    on public."Requests" ("OdToId")
    where ("IsDeleted" = false);

create index "IX_Requests_SeasonId"
    on public."Requests" ("SeasonId")
    where ("IsDeleted" = false);

create index "IX_Requests_UserId"
    on public."Requests" ("UserId")
    where ("IsDeleted" = false);

create index "IX_Requests_CurrencyId"
    on public."Requests" ("CurrencyId")
    where ("IsDeleted" = false);

create index "IX_Requests_DestinationId"
    on public."Requests" ("DestinationId")
    where ("IsDeleted" = false);

create index "IX_Requests_RoutingId"
    on public."Requests" ("RoutingId")
    where ("IsDeleted" = false);

create index "IX_Requests_ProviderId"
    on public."Requests" ("ProviderId")
    where ("IsDeleted" = false);

