create table if not exists public."__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table public."__EFMigrationsHistory"
    owner to neos;

create table if not exists public."Airports"
(
    "Id"        integer generated by default as identity
        constraint "PK_Airports"
            primary key,
    "IataCode"  varchar(32)              not null,
    "IcaoCode"  varchar(32)              not null,
    "Name"      varchar(256)             not null,
    "City"      varchar(256)             not null,
    "CreatedAt" timestamp with time zone not null,
    "CreatedBy" integer                  not null,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" integer,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "IsDeleted" boolean                  not null
);

alter table public."Airports"
    owner to neos;

create index if not exists "IX_Airports_IataCode"
    on public."Airports" ("IataCode")
    where ("IsDeleted" = false);

create index if not exists "IX_Airports_IsDeleted"
    on public."Airports" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."Companies"
(
    "Id"           integer generated by default as identity
        constraint "PK_Companies"
            primary key,
    "Code"         varchar(5)               not null,
    "Name"         varchar(512)             not null,
    "Address"      varchar(512)             not null,
    "City"         varchar(64)              not null,
    "PostalCode"   varchar(5)               not null,
    "State"        varchar(64),
    "Country"      varchar(64)              not null,
    "VatCode"      varchar(64)              not null,
    "PhoneNumber"  varchar(64)              not null,
    "FaxNumber"    varchar(64),
    "EmailAddress" varchar(64)              not null,
    "Role"         integer                  not null
        constraint "CKE_Role"
            check (("Role" >= 0) AND ("Role" <= 7)),
    "CreatedAt"    timestamp with time zone not null,
    "CreatedBy"    integer                  not null,
    "UpdatedAt"    timestamp with time zone,
    "UpdatedBy"    integer,
    "DeletedAt"    timestamp with time zone,
    "DeletedBy"    integer,
    "IsDeleted"    boolean                  not null
);

comment on column public."Companies"."Role" is 'EnmCompanyRole flags ( None = 0, Supplier = 1, Broker = 2, Customer = 4 )';

alter table public."Companies"
    owner to neos;

create index if not exists "IX_Companies_IsDeleted"
    on public."Companies" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."ContractTypes"
(
    "Id"          integer generated by default as identity
        constraint "PK_ContractTypes"
            primary key,
    "Name"        varchar(64)              not null,
    "Description" varchar(256)             not null,
    "CreatedAt"   timestamp with time zone not null,
    "CreatedBy"   integer                  not null,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   integer,
    "DeletedAt"   timestamp with time zone,
    "DeletedBy"   integer,
    "IsDeleted"   boolean                  not null
);

alter table public."ContractTypes"
    owner to neos;

create index if not exists "IX_ContractTypes_IsDeleted"
    on public."ContractTypes" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."Fares"
(
    "Id"                    integer generated by default as identity
        constraint "PK_Fares"
            primary key,
    "FareBasis"             varchar(256)             not null,
    "GridClass"             integer                  not null
        constraint "CKE_GridClass"
            check ("GridClass" = ANY (ARRAY [0, 1, 2, 3, 4, 5, 6])),
    "Value"                 numeric(6, 3)            not null,
    "ValidityFrom"          date                     not null,
    "ValidityTo"            date                     not null,
    "MinPassengers"         integer                  not null,
    "Min"                   integer,
    "Max"                   integer,
    "IsDefault"             boolean                  not null,
    "YthPercentageDiscount" integer                  not null,
    "ChdPercentageDiscount" integer                  not null,
    "InfPercentageDiscount" integer                  not null,
    "DataOwningCarrierCode" integer                  not null
        constraint "CKE_DataOwningCarrierCode"
            check ("DataOwningCarrierCode" = 0),
    "TariffNumber"          integer                  not null
        constraint "CKE_TariffNumber"
            check ("TariffNumber" = ANY (ARRAY [4, 21, 22, 23, 27, 302, 304, 364])),
    "RuleNumber"            varchar(64)              not null,
    "FareType"              integer                  not null
        constraint "CKE_FareType"
            check ("FareType" = ANY (ARRAY [0, 1])),
    "OWRT"                  integer                  not null
        constraint "CKE_OWRT"
            check ("OWRT" = ANY (ARRAY [1, 2])),
    "RoutingNumber"         integer                  not null,
    "FootNote"              text,
    "CreatedAt"             timestamp with time zone not null,
    "CreatedBy"             integer                  not null,
    "UpdatedAt"             timestamp with time zone,
    "UpdatedBy"             integer,
    "DeletedAt"             timestamp with time zone,
    "DeletedBy"             integer,
    "IsDeleted"             boolean                  not null
);

comment on column public."Fares"."GridClass" is 'EnmFareGridClass values ( A = 0, S = 1, J = 2, X = 3, V = 4, Z = 5, I = 6 )';

comment on column public."Fares"."DataOwningCarrierCode" is 'EnmFareDataOwningCarrierCode values ( NO = 0 )';

comment on column public."Fares"."TariffNumber" is 'EnmFareTariffNumber values ( N004 = 4, N021 = 21, N022 = 22, N023 = 23, N027 = 27, N302 = 302, N304 = 304, N364 = 364 )';

comment on column public."Fares"."FareType" is 'EnmFareType values ( EU = 0, WR = 1 )';

comment on column public."Fares"."OWRT" is 'EnmFareOwrt values ( OneWay = 1, RoundTrip = 2 )';

alter table public."Fares"
    owner to neos;

create index if not exists "IX_Fares_FareBasis"
    on public."Fares" ("FareBasis")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_IsDeleted"
    on public."Fares" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_TariffNumber"
    on public."Fares" ("TariffNumber")
    where ("IsDeleted" = false);

create table if not exists public."FlightIntegrations"
(
    "Id"                            integer generated by default as identity
        constraint "PK_FlightIntegrations"
            primary key,
    "SegmentFlightIdentifier"       varchar(64)              not null,
    "SegmentAirline"                varchar(64)              not null,
    "SegmentFlightNumber"           varchar(64)              not null,
    "SegmentDepartureDateTime"      timestamp with time zone not null,
    "SegmentArrivalDateTime"        timestamp with time zone not null,
    "SegmentBoardingPoint"          varchar(64)              not null,
    "SegmentDeplaningPoint"         varchar(64)              not null,
    "SegmentAircraftOwner"          varchar(64)              not null,
    "SegmentCockpitCrew"            varchar(64)              not null,
    "SegmentCabinCrew"              varchar(64)              not null,
    "EquipmentAircraftType"         varchar(64)              not null,
    "EquipmentDesignators"          varchar(64)              not null,
    "EquipmentServiceType"          varchar(64)              not null,
    "EquipmentAcvYCompartmentSeats" integer                  not null,
    "EquipmentAcvCCompartmentSeats" integer                  not null,
    "Routing"                       varchar(64)              not null,
    "RotationCode"                  varchar(64)              not null,
    "FlightType"                    integer                  not null
        constraint "CKE_FlightType"
            check ("FlightType" = ANY (ARRAY [0, 1])),
    "CreatedAt"                     timestamp with time zone not null,
    "CreatedBy"                     integer                  not null,
    "UpdatedAt"                     timestamp with time zone,
    "UpdatedBy"                     integer,
    "DeletedAt"                     timestamp with time zone,
    "DeletedBy"                     integer,
    "IsDeleted"                     boolean                  not null
);

comment on column public."FlightIntegrations"."FlightType" is 'EnmFlightIntegrationFlightType values ( Real = 0, Virtual = 1 )';

alter table public."FlightIntegrations"
    owner to neos;

create index if not exists "IX_FlightIntegrations_IsDeleted"
    on public."FlightIntegrations" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_RotationCode"
    on public."FlightIntegrations" ("RotationCode")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_Routing"
    on public."FlightIntegrations" ("Routing")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_SegmentArrivalDateTime"
    on public."FlightIntegrations" ("SegmentArrivalDateTime")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_SegmentBoardingPoint"
    on public."FlightIntegrations" ("SegmentBoardingPoint")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_SegmentDepartureDateTime"
    on public."FlightIntegrations" ("SegmentDepartureDateTime")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_SegmentDeplaningPoint"
    on public."FlightIntegrations" ("SegmentDeplaningPoint")
    where ("IsDeleted" = false);

create index if not exists "IX_FlightIntegrations_SegmentFlightNumber"
    on public."FlightIntegrations" ("SegmentFlightNumber")
    where ("IsDeleted" = false);

create table if not exists public."PrintModels"
(
    "Id"          integer generated by default as identity
        constraint "PK_PrintModels"
            primary key,
    "Name"        varchar(64)              not null,
    "Description" varchar(256)             not null,
    "CreatedAt"   timestamp with time zone not null,
    "CreatedBy"   integer                  not null,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   integer,
    "DeletedAt"   timestamp with time zone,
    "DeletedBy"   integer,
    "IsDeleted"   boolean                  not null
);

alter table public."PrintModels"
    owner to neos;

create index if not exists "IX_PrintModels_IsDeleted"
    on public."PrintModels" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."ReasonForIssuanceCodes"
(
    "Id"          integer generated by default as identity
        constraint "PK_ReasonForIssuanceCodes"
            primary key,
    "Code"        varchar(5)               not null,
    "Description" varchar(512)             not null,
    "CreatedAt"   timestamp with time zone not null,
    "CreatedBy"   integer                  not null,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   integer,
    "DeletedAt"   timestamp with time zone,
    "DeletedBy"   integer,
    "IsDeleted"   boolean                  not null
);

alter table public."ReasonForIssuanceCodes"
    owner to neos;

create index if not exists "IX_ReasonForIssuanceCodes_IsDeleted"
    on public."ReasonForIssuanceCodes" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."Roles"
(
    "Id"               integer generated by default as identity
        constraint "PK_Roles"
            primary key,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

alter table public."Roles"
    owner to neos;

create unique index if not exists "RoleNameIndex"
    on public."Roles" ("NormalizedName");

create table if not exists public."Seasons"
(
    "Id"          integer generated by default as identity
        constraint "PK_Seasons"
            primary key,
    "Name"        varchar(64)              not null,
    "Description" varchar(256)             not null,
    "DateFrom"    date                     not null,
    "DateTo"      date                     not null,
    "CreatedAt"   timestamp with time zone not null,
    "CreatedBy"   integer                  not null,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   integer,
    "DeletedAt"   timestamp with time zone,
    "DeletedBy"   integer,
    "IsDeleted"   boolean                  not null
);

alter table public."Seasons"
    owner to neos;

create index if not exists "IX_Seasons_IsDeleted"
    on public."Seasons" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."UnitOfMeasures"
(
    "Id"       integer generated by default as identity
        constraint "PK_UnitOfMeasures"
            primary key,
    "Symbol"   varchar(32) not null,
    "Name"     varchar(64) not null,
    "Category" integer     not null
        constraint "CKE_Category"
            check ("Category" = ANY (ARRAY [0, 1, 2, 3, 4, 5]))
);

comment on column public."UnitOfMeasures"."Category" is 'EnmUnitOfMeasureCategory values ( AbsoluteValue = 0, Percentage = 1, Currency = 2, ExchangeRate = 3, Ratio = 4, DateOnly = 5 )';

alter table public."UnitOfMeasures"
    owner to neos;

create unique index if not exists "IX_UnitOfMeasures_Symbol"
    on public."UnitOfMeasures" ("Symbol");

create table if not exists public."Users"
(
    "Id"                     integer generated by default as identity
        constraint "PK_Users"
            primary key,
    "FirstName"              text                     not null,
    "LastName"               text                     not null,
    "CompanyId"              integer                  not null
        constraint "FK_Users_Companies_CompanyId"
            references public."Companies"
            on delete cascade,
    "RefreshToken"           text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    "CreatedAt"              timestamp with time zone not null,
    "CreatedBy"              integer                  not null,
    "UpdatedAt"              timestamp with time zone,
    "UpdatedBy"              integer,
    "DeletedAt"              timestamp with time zone,
    "DeletedBy"              integer,
    "IsDeleted"              boolean                  not null,
    "UserName"               varchar(256)             not null,
    "NormalizedUserName"     varchar(256)             not null,
    "Email"                  varchar(256),
    "NormalizedEmail"        varchar(256),
    "EmailConfirmed"         boolean                  not null,
    "PasswordHash"           text,
    "SecurityStamp"          text,
    "ConcurrencyStamp"       text,
    "PhoneNumber"            text,
    "PhoneNumberConfirmed"   boolean                  not null,
    "TwoFactorEnabled"       boolean                  not null,
    "LockoutEnd"             timestamp with time zone,
    "LockoutEnabled"         boolean                  not null,
    "AccessFailedCount"      integer                  not null
);

alter table public."Users"
    owner to neos;

create unique index if not exists "EmailIndex"
    on public."Users" ("NormalizedEmail")
    where ("IsDeleted" = false);

create index if not exists "IX_Users_CompanyId"
    on public."Users" ("CompanyId")
    where ("IsDeleted" = false);

create index if not exists "IX_Users_IsDeleted"
    on public."Users" ("IsDeleted")
    where ("IsDeleted" = false);

create unique index if not exists "UserNameIndex"
    on public."Users" ("NormalizedUserName")
    where ("IsDeleted" = false);

create table if not exists public."FareApplicabilities"
(
    "Id"                   integer generated by default as identity
        constraint "PK_FareApplicabilities"
            primary key,
    "FareId"               integer                  not null
        constraint "FK_FareApplicabilities_Fares_FareId"
            references public."Fares"
            on delete cascade,
    "Category"             integer                  not null
        constraint "CKE_Category"
            check ("Category" = ANY (ARRAY [0, 1])),
    "IataOrigin"           varchar(64)              not null,
    "IataDestination"      varchar(256)             not null,
    "FlightStartDate"      date                     not null,
    "FlightEndDate"        date                     not null,
    "BookingStartDate"     date                     not null,
    "BookingEndDate"       date                     not null,
    "AdvancedPurchaseDays" integer                  not null,
    "LastMinuteHours"      integer                  not null,
    "StartTime"            time                     not null,
    "EndTime"              time                     not null,
    "CreatedAt"            timestamp with time zone not null,
    "CreatedBy"            integer                  not null,
    "UpdatedAt"            timestamp with time zone,
    "UpdatedBy"            integer,
    "DeletedAt"            timestamp with time zone,
    "DeletedBy"            integer,
    "IsDeleted"            boolean                  not null
);

comment on column public."FareApplicabilities"."Category" is 'EnmFareApplicabilityCategory values ( Relax1 = 0, Freedomy = 1 )';

alter table public."FareApplicabilities"
    owner to neos;

create index if not exists "IX_FareApplicabilities_Category"
    on public."FareApplicabilities" ("Category")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_FareId"
    on public."FareApplicabilities" ("FareId")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_FlightEndDate"
    on public."FareApplicabilities" ("FlightEndDate")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_FlightStartDate"
    on public."FareApplicabilities" ("FlightStartDate")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_IataDestination"
    on public."FareApplicabilities" ("IataDestination")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_IataOrigin"
    on public."FareApplicabilities" ("IataOrigin")
    where ("IsDeleted" = false);

create index if not exists "IX_FareApplicabilities_IsDeleted"
    on public."FareApplicabilities" ("IsDeleted")
    where ("IsDeleted" = false);

create table if not exists public."SpecialTypes"
(
    "Id"                      integer generated by default as identity
        constraint "PK_SpecialTypes"
            primary key,
    "IataCode"                varchar(32)              not null,
    "AtpcoSubCode"            varchar(32),
    "DescriptionOne"          varchar(512),
    "DescriptionTwo"          varchar(512),
    "CommercialName"          varchar(256),
    "ReasonForIssuanceCodeId" integer                  not null
        constraint "FK_SpecialTypes_ReasonForIssuanceCodes_ReasonForIssuanceCodeId"
            references public."ReasonForIssuanceCodes"
            on delete cascade,
    "CreatedAt"               timestamp with time zone not null,
    "CreatedBy"               integer                  not null,
    "UpdatedAt"               timestamp with time zone,
    "UpdatedBy"               integer,
    "DeletedAt"               timestamp with time zone,
    "DeletedBy"               integer,
    "IsDeleted"               boolean                  not null
);

alter table public."SpecialTypes"
    owner to neos;

create index if not exists "IX_SpecialTypes_IsDeleted"
    on public."SpecialTypes" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_SpecialTypes_ReasonForIssuanceCodeId"
    on public."SpecialTypes" ("ReasonForIssuanceCodeId");

create table if not exists public."RoleClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_RoleClaims"
            primary key,
    "RoleId"     integer not null
        constraint "FK_RoleClaims_Roles_RoleId"
            references public."Roles"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table public."RoleClaims"
    owner to neos;

create index if not exists "IX_RoleClaims_RoleId"
    on public."RoleClaims" ("RoleId");

create table if not exists public."MasterContracts"
(
    "Id"               integer generated by default as identity
        constraint "PK_MasterContracts"
            primary key,
    "ContractNumber"   varchar(7)               not null,
    "Title"            varchar(256)             not null,
    "MainContractDate" date                     not null,
    "ContractDate"     date                     not null,
    "ContractTypeId"   integer                  not null
        constraint "FK_MasterContracts_ContractTypes_ContractTypeId"
            references public."ContractTypes"
            on delete cascade,
    "SupplierId"       integer                  not null
        constraint "FK_MasterContracts_Companies_SupplierId"
            references public."Companies"
            on delete cascade,
    "BrokerId"         integer                  not null
        constraint "FK_MasterContracts_Companies_BrokerId"
            references public."Companies"
            on delete cascade,
    "SeasonId"         integer                  not null
        constraint "FK_MasterContracts_Seasons_SeasonId"
            references public."Seasons"
            on delete cascade,
    "PrintModelId"     integer                  not null
        constraint "FK_MasterContracts_PrintModels_PrintModelId"
            references public."PrintModels"
            on delete cascade,
    "CurrencyId"       integer                  not null,
    "CustomerId"       integer                  not null
        constraint "FK_MasterContracts_Companies_CustomerId"
            references public."Companies"
            on delete cascade,
    "BillingRole"      boolean                  not null,
    "RejectionReason"  text,
    "Notes"            text,
    "Status"           integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4])),
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

comment on column public."MasterContracts"."Status" is 'EnmMasterContractStatus values ( Requested = 0, Rejected = 1, InProgress = 2, Quoted = 3, Confirmed = 4 )';

alter table public."MasterContracts"
    owner to neos;

create index if not exists "IX_MasterContracts_BrokerId"
    on public."MasterContracts" ("BrokerId")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_ContractTypeId"
    on public."MasterContracts" ("ContractTypeId")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_CustomerId"
    on public."MasterContracts" ("CustomerId")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_IsDeleted"
    on public."MasterContracts" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_PrintModelId"
    on public."MasterContracts" ("PrintModelId")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_SeasonId"
    on public."MasterContracts" ("SeasonId")
    where ("IsDeleted" = false);

create index if not exists "IX_MasterContracts_SupplierId"
    on public."MasterContracts" ("SupplierId")
    where ("IsDeleted" = false);

create table if not exists public."Requests"
(
    "Id"               integer generated by default as identity
        constraint "PK_Requests"
            primary key,
    "UserId"           integer                  not null
        constraint "FK_Requests_Users_UserId"
            references public."Users"
            on delete cascade,
    "OdFromId"         integer                  not null
        constraint "FK_Requests_Airports_OdFromId"
            references public."Airports"
            on delete cascade,
    "OdToId"           integer                  not null
        constraint "FK_Requests_Airports_OdToId"
            references public."Airports"
            on delete cascade,
    "DateFrom"         date                     not null,
    "DateTo"           date                     not null,
    "OperativeDay"     integer                  not null,
    "DestinationId"    integer                  not null,
    "AircraftTypeId"   integer,
    "SeasonId"         integer                  not null
        constraint "FK_Requests_Seasons_SeasonId"
            references public."Seasons"
            on delete cascade,
    "Year"             smallint                 not null,
    "CurrencyId"       integer,
    "ContractTypeId"   integer
        constraint "FK_Requests_ContractTypes_ContractTypeId"
            references public."ContractTypes",
    "RejectionReason"  text,
    "Status"           integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4, 5])),
    "RoutingId"        integer,
    "GuaranteedSeatsP" integer                  not null,
    "GuaranteedSeatsY" integer                  not null,
    "GuaranteedSeatsF" integer                  not null,
    "ReleaseSeatsP"    integer                  not null,
    "ReleaseSeatsY"    integer                  not null,
    "ReleaseSeatsF"    integer                  not null,
    "Frequency"        integer                  not null
        constraint "CKE_Frequency"
            check ("Frequency" = ANY (ARRAY [0, 1, 2, 3])),
    "Notes"            text,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

comment on column public."Requests"."Status" is 'EnmRequestStatus values ( Requested = 0, Rejected = 1, InProgress = 2, Quoted = 3, PartiallyConfirmed = 4, Confirmed = 5 )';

comment on column public."Requests"."Frequency" is 'EnmOriginDestinationFrequency values ( Daily = 0, Weekly = 1, DD21 = 2, Monthly = 3 )';

alter table public."Requests"
    owner to neos;

create index if not exists "IX_Requests_ContractTypeId"
    on public."Requests" ("ContractTypeId")
    where ("IsDeleted" = false);

create index if not exists "IX_Requests_IsDeleted"
    on public."Requests" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Requests_OdFromId"
    on public."Requests" ("OdFromId")
    where ("IsDeleted" = false);

create index if not exists "IX_Requests_OdToId"
    on public."Requests" ("OdToId")
    where ("IsDeleted" = false);

create index if not exists "IX_Requests_SeasonId"
    on public."Requests" ("SeasonId")
    where ("IsDeleted" = false);

create index if not exists "IX_Requests_UserId"
    on public."Requests" ("UserId")
    where ("IsDeleted" = false);

create table if not exists public."UserClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_UserClaims"
            primary key,
    "UserId"     integer not null
        constraint "FK_UserClaims_Users_UserId"
            references public."Users"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table public."UserClaims"
    owner to neos;

create index if not exists "IX_UserClaims_UserId"
    on public."UserClaims" ("UserId");

create table if not exists public."UserLogins"
(
    "LoginProvider"       text    not null,
    "ProviderKey"         text    not null,
    "ProviderDisplayName" text,
    "UserId"              integer not null
        constraint "FK_UserLogins_Users_UserId"
            references public."Users"
            on delete cascade,
    constraint "PK_UserLogins"
        primary key ("LoginProvider", "ProviderKey")
);

alter table public."UserLogins"
    owner to neos;

create index if not exists "IX_UserLogins_UserId"
    on public."UserLogins" ("UserId");

create table if not exists public."UserRoles"
(
    "UserId" integer not null
        constraint "FK_UserRoles_Users_UserId"
            references public."Users"
            on delete cascade,
    "RoleId" integer not null
        constraint "FK_UserRoles_Roles_RoleId"
            references public."Roles"
            on delete cascade,
    constraint "PK_UserRoles"
        primary key ("UserId", "RoleId")
);

alter table public."UserRoles"
    owner to neos;

create index if not exists "IX_UserRoles_RoleId"
    on public."UserRoles" ("RoleId");

create table if not exists public."UserTokens"
(
    "UserId"        integer not null
        constraint "FK_UserTokens_Users_UserId"
            references public."Users"
            on delete cascade,
    "LoginProvider" text    not null,
    "Name"          text    not null,
    "Value"         text,
    constraint "PK_UserTokens"
        primary key ("UserId", "LoginProvider", "Name")
);

alter table public."UserTokens"
    owner to neos;

create table if not exists public."FareSpecialServices"
(
    "Id"        integer generated by default as identity
        constraint "PK_FareSpecialServices"
            primary key,
    "FareId"    integer                  not null
        constraint "FK_FareSpecialServices_Fares_FareId"
            references public."Fares"
            on delete cascade,
    "Quantity"  integer                  not null,
    "TypeId"    integer                  not null
        constraint "FK_FareSpecialServices_SpecialTypes_TypeId"
            references public."SpecialTypes"
            on delete cascade,
    "CreatedAt" timestamp with time zone not null,
    "CreatedBy" integer                  not null,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" integer,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "IsDeleted" boolean                  not null
);

alter table public."FareSpecialServices"
    owner to neos;

create index if not exists "IX_FareSpecialServices_FareId"
    on public."FareSpecialServices" ("FareId")
    where ("IsDeleted" = false);

create index if not exists "IX_FareSpecialServices_IsDeleted"
    on public."FareSpecialServices" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_FareSpecialServices_TypeId"
    on public."FareSpecialServices" ("TypeId")
    where ("IsDeleted" = false);

create table if not exists public."Incentives"
(
    "Id"                               integer generated by default as identity
        constraint "PK_Incentives"
            primary key,
    "MasterContractId"                 integer                  not null
        constraint "FK_Incentives_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "Name"                             varchar(256)             not null,
    "ValidityFrom"                     date                     not null,
    "ValidityTo"                       date                     not null,
    "TargetType"                       integer                  not null
        constraint "CKE_TargetType"
            check ("TargetType" = ANY (ARRAY [0, 1, 2])),
    "Target"                           integer                  not null,
    "TargetUnitOfMeasureId"            integer                  not null
        constraint "FK_Incentives_UnitOfMeasures_TargetUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "PremiumCommission"                numeric(10, 2)           not null,
    "PremiumCommissionUnitOfMeasureId" integer                  not null
        constraint "FK_Incentives_UnitOfMeasures_PremiumCommissionUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "EconomyCommission"                numeric(10, 2)           not null,
    "EconomyCommissionUnitOfMeasureId" integer                  not null
        constraint "FK_Incentives_UnitOfMeasures_EconomyCommissionUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "Notes"                            text,
    "CreatedAt"                        timestamp with time zone not null,
    "CreatedBy"                        integer                  not null,
    "UpdatedAt"                        timestamp with time zone,
    "UpdatedBy"                        integer,
    "DeletedAt"                        timestamp with time zone,
    "DeletedBy"                        integer,
    "IsDeleted"                        boolean                  not null
);

comment on column public."Incentives"."TargetType" is 'EnmIncentiveTargetType values ( PracticesNumber = 0, TicketsIssuedNumber = 1, SeatsToSellForBlockSpacePercentage = 2 )';

alter table public."Incentives"
    owner to neos;

create index if not exists "IX_Incentives_EconomyCommissionUnitOfMeasureId"
    on public."Incentives" ("EconomyCommissionUnitOfMeasureId")
    where ("IsDeleted" = false);

create index if not exists "IX_Incentives_IsDeleted"
    on public."Incentives" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Incentives_MasterContractId"
    on public."Incentives" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_Incentives_PremiumCommissionUnitOfMeasureId"
    on public."Incentives" ("PremiumCommissionUnitOfMeasureId")
    where ("IsDeleted" = false);

create index if not exists "IX_Incentives_TargetUnitOfMeasureId"
    on public."Incentives" ("TargetUnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."Materializations"
(
    "Id"                                 integer generated by default as identity
        constraint "PK_Materializations"
            primary key,
    "MasterContractId"                   integer                  not null
        constraint "FK_Materializations_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "Name"                               varchar(256)             not null,
    "ValidityFrom"                       date                     not null,
    "ValidityTo"                         date                     not null,
    "Type"                               integer                  not null
        constraint "CKE_Type"
            check ("Type" = ANY (ARRAY [0, 1, 2])),
    "Target"                             integer                  not null,
    "TargetUnitOfMeasureId"              integer                  not null
        constraint "FK_Materializations_UnitOfMeasures_TargetUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "PenaltyCommission"                  numeric(10, 2)           not null,
    "PenaltyCommissionUnitOfMeasureId"   integer                  not null
        constraint "FK_Materializations_UnitOfMeasures_PenaltyCommissionUnitOfMeas~"
            references public."UnitOfMeasures"
            on delete cascade,
    "IncentiveCommission"                numeric(10, 2)           not null,
    "IncentiveCommissionUnitOfMeasureId" integer                  not null
        constraint "FK_Materializations_UnitOfMeasures_IncentiveCommissionUnitOfMe~"
            references public."UnitOfMeasures"
            on delete cascade,
    "CreatedAt"                          timestamp with time zone not null,
    "CreatedBy"                          integer                  not null,
    "UpdatedAt"                          timestamp with time zone,
    "UpdatedBy"                          integer,
    "DeletedAt"                          timestamp with time zone,
    "DeletedBy"                          integer,
    "IsDeleted"                          boolean                  not null
);

comment on column public."Materializations"."Type" is 'EnmMaterializationType values ( PracticesNumber = 0, TicketsIssuedNumber = 1, SeatsToSellForBlockSpacePercentage = 2 )';

alter table public."Materializations"
    owner to neos;

create index if not exists "IX_Materializations_IncentiveCommissionUnitOfMeasureId"
    on public."Materializations" ("IncentiveCommissionUnitOfMeasureId")
    where ("IsDeleted" = false);

create index if not exists "IX_Materializations_IsDeleted"
    on public."Materializations" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Materializations_MasterContractId"
    on public."Materializations" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_Materializations_PenaltyCommissionUnitOfMeasureId"
    on public."Materializations" ("PenaltyCommissionUnitOfMeasureId")
    where ("IsDeleted" = false);

create index if not exists "IX_Materializations_TargetUnitOfMeasureId"
    on public."Materializations" ("TargetUnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."OperativeProcedures"
(
    "Id"                         integer generated by default as identity
        constraint "PK_OperativeProcedures"
            primary key,
    "MasterContractId"           integer                  not null
        constraint "FK_OperativeProcedures_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "PnrModeTypeId"              integer                  not null,
    "CreationDateLimit"          integer                  not null,
    "SendPassengerListDateLimit" integer                  not null,
    "SendingModeTypeId"          integer                  not null,
    "IssuingModeTypeId"          integer                  not null,
    "TicketingDateLimit"         integer                  not null,
    "EmailAddress"               varchar(256),
    "LuggageTypeId"              integer                  not null,
    "WeightTypeId"               integer                  not null,
    "SizeTypeId"                 integer                  not null,
    "AllowanceBaggage"           integer                  not null,
    "CreatedAt"                  timestamp with time zone not null,
    "CreatedBy"                  integer                  not null,
    "UpdatedAt"                  timestamp with time zone,
    "UpdatedBy"                  integer,
    "DeletedAt"                  timestamp with time zone,
    "DeletedBy"                  integer,
    "IsDeleted"                  boolean                  not null
);

alter table public."OperativeProcedures"
    owner to neos;

create index if not exists "IX_OperativeProcedures_IsDeleted"
    on public."OperativeProcedures" ("IsDeleted")
    where ("IsDeleted" = false);

create unique index if not exists "IX_OperativeProcedures_MasterContractId"
    on public."OperativeProcedures" ("MasterContractId")
    where ("IsDeleted" = false);

create table if not exists public."Proposals"
(
    "Id"               integer generated by default as identity
        constraint "PK_Proposals"
            primary key,
    "RequestId"        integer                  not null
        constraint "FK_Proposals_Requests_RequestId"
            references public."Requests"
            on delete cascade,
    "MasterContractId" integer                  not null
        constraint "FK_Proposals_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "CustomerId"       integer                  not null
        constraint "FK_Proposals_Companies_CustomerId"
            references public."Companies"
            on delete cascade,
    "OdFromId"         integer                  not null
        constraint "FK_Proposals_Airports_OdFromId"
            references public."Airports"
            on delete cascade,
    "OdToId"           integer                  not null
        constraint "FK_Proposals_Airports_OdToId"
            references public."Airports"
            on delete cascade,
    "DateFrom"         date                     not null,
    "DateTo"           date                     not null,
    "OperativeDay"     integer                  not null,
    "DestinationId"    integer                  not null,
    "AircraftTypeId"   integer,
    "SeasonId"         integer                  not null
        constraint "FK_Proposals_Seasons_SeasonId"
            references public."Seasons"
            on delete cascade,
    "Year"             smallint                 not null,
    "CurrencyId"       integer,
    "ContractTypeId"   integer
        constraint "FK_Proposals_ContractTypes_ContractTypeId"
            references public."ContractTypes",
    "RejectionReason"  text,
    "Status"           integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4])),
    "RoutingId"        integer,
    "GuaranteedSeatsP" integer                  not null,
    "GuaranteedSeatsY" integer                  not null,
    "GuaranteedSeatsF" integer                  not null,
    "ReleaseSeatsP"    integer                  not null,
    "ReleaseSeatsY"    integer                  not null,
    "ReleaseSeatsF"    integer                  not null,
    "Frequency"        integer                  not null
        constraint "CKE_Frequency"
            check ("Frequency" = ANY (ARRAY [0, 1, 2, 3])),
    "Notes"            text,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

comment on column public."Proposals"."Status" is 'EnmProposalStatus values ( Sent = 0, Rejected = 1, InProgress = 2, Confirmed = 3, Modified = 4 )';

comment on column public."Proposals"."Frequency" is 'EnmOriginDestinationFrequency values ( Daily = 0, Weekly = 1, DD21 = 2, Monthly = 3 )';

alter table public."Proposals"
    owner to neos;

create index if not exists "IX_Proposals_ContractTypeId"
    on public."Proposals" ("ContractTypeId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_CustomerId"
    on public."Proposals" ("CustomerId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_IsDeleted"
    on public."Proposals" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_MasterContractId"
    on public."Proposals" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_OdFromId"
    on public."Proposals" ("OdFromId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_OdToId"
    on public."Proposals" ("OdToId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_RequestId"
    on public."Proposals" ("RequestId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_SeasonId"
    on public."Proposals" ("SeasonId")
    where ("IsDeleted" = false);

create table if not exists public."IncentivePayments"
(
    "IncentiveId" integer not null
        constraint "FK_IncentivePayments_Incentives_IncentiveId"
            references public."Incentives"
            on delete cascade,
    "PaymentId"   integer not null,
    constraint "PK_IncentivePayments"
        primary key ("IncentiveId", "PaymentId")
);

alter table public."IncentivePayments"
    owner to neos;

create table if not exists public."IncentiveTriggers"
(
    "IncentiveId" integer not null
        constraint "FK_IncentiveTriggers_Incentives_IncentiveId"
            references public."Incentives"
            on delete cascade,
    "TriggerId"   integer not null,
    constraint "PK_IncentiveTriggers"
        primary key ("IncentiveId", "TriggerId")
);

alter table public."IncentiveTriggers"
    owner to neos;

create table if not exists public."Series"
(
    "Id"              integer generated by default as identity
        constraint "PK_Series"
            primary key,
    "ProposalId"      integer                  not null
        constraint "FK_Series_Proposals_ProposalId"
            references public."Proposals"
            on delete cascade,
    "Name"            varchar(256)             not null,
    "RejectionReason" text,
    "Status"          integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4])),
    "Notes"           text,
    "CreatedAt"       timestamp with time zone not null,
    "CreatedBy"       integer                  not null,
    "UpdatedAt"       timestamp with time zone,
    "UpdatedBy"       integer,
    "DeletedAt"       timestamp with time zone,
    "DeletedBy"       integer,
    "IsDeleted"       boolean                  not null
);

comment on column public."Series"."Status" is 'EnmSeriesStatus values ( Sent = 0, Rejected = 1, InProgress = 2, Confirmed = 3, Modified = 4 )';

alter table public."Series"
    owner to neos;

create index if not exists "IX_Series_IsDeleted"
    on public."Series" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Series_ProposalId"
    on public."Series" ("ProposalId")
    where ("IsDeleted" = false);

create table if not exists public."IncentiveSeries"
(
    "IncentiveId" integer not null
        constraint "FK_IncentiveSeries_Incentives_IncentiveId"
            references public."Incentives"
            on delete cascade,
    "SeriesId"    integer not null
        constraint "FK_IncentiveSeries_Series_SeriesId"
            references public."Series"
            on delete cascade,
    constraint "PK_IncentiveSeries"
        primary key ("IncentiveId", "SeriesId")
);

alter table public."IncentiveSeries"
    owner to neos;

create index if not exists "IX_IncentiveSeries_SeriesId"
    on public."IncentiveSeries" ("SeriesId");

create table if not exists public."MaterializationSeries"
(
    "MaterializationId" integer not null
        constraint "FK_MaterializationSeries_Materializations_MaterializationId"
            references public."Materializations"
            on delete cascade,
    "SeriesId"          integer not null
        constraint "FK_MaterializationSeries_Series_SeriesId"
            references public."Series"
            on delete cascade,
    constraint "PK_MaterializationSeries"
        primary key ("MaterializationId", "SeriesId")
);

alter table public."MaterializationSeries"
    owner to neos;

create index if not exists "IX_MaterializationSeries_SeriesId"
    on public."MaterializationSeries" ("SeriesId");

create table if not exists public."OriginDestinations"
(
    "Id"               integer generated by default as identity
        constraint "PK_OriginDestinations"
            primary key,
    "SeriesId"         integer                  not null
        constraint "FK_OriginDestinations_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "Frequency"        integer                  not null
        constraint "CKE_Frequency"
            check ("Frequency" = ANY (ARRAY [0, 1, 2, 3])),
    "Direction"        integer                  not null
        constraint "CKE_Direction"
            check ("Direction" = ANY (ARRAY [0, 1])),
    "DateFrom"         date                     not null,
    "DateTo"           date                     not null,
    "BoardingPointId"  integer                  not null
        constraint "FK_OriginDestinations_Airports_BoardingPointId"
            references public."Airports"
            on delete cascade,
    "DeplaningPointId" integer                  not null
        constraint "FK_OriginDestinations_Airports_DeplaningPointId"
            references public."Airports"
            on delete cascade,
    "AverageProSeat"   integer                  not null,
    "Invoice"          boolean                  not null,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

comment on column public."OriginDestinations"."Frequency" is 'EnmOriginDestinationFrequency values ( Daily = 0, Weekly = 1, DD21 = 2, Monthly = 3 )';

comment on column public."OriginDestinations"."Direction" is 'EnmOriginDestinationDirection values ( Outbound = 0, Inbound = 1 )';

alter table public."OriginDestinations"
    owner to neos;

create index if not exists "IX_OriginDestinations_BoardingPointId"
    on public."OriginDestinations" ("BoardingPointId")
    where ("IsDeleted" = false);

create index if not exists "IX_OriginDestinations_DeplaningPointId"
    on public."OriginDestinations" ("DeplaningPointId")
    where ("IsDeleted" = false);

create index if not exists "IX_OriginDestinations_IsDeleted"
    on public."OriginDestinations" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_OriginDestinations_SeriesId"
    on public."OriginDestinations" ("SeriesId")
    where ("IsDeleted" = false);

create table if not exists public."SpecialServices"
(
    "Id"               integer generated by default as identity
        constraint "PK_SpecialServices"
            primary key,
    "MasterContractId" integer                  not null
        constraint "FK_SpecialServices_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "SeriesId"         integer
        constraint "FK_SpecialServices_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "TypeId"           integer                  not null
        constraint "FK_SpecialServices_SpecialTypes_TypeId"
            references public."SpecialTypes"
            on delete cascade,
    "Price"            numeric(10, 2)           not null,
    "CurrencyId"       integer                  not null,
    "ValidityFrom"     date,
    "ValidityTo"       date,
    "Allowance"        integer,
    "Commission"       integer,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

alter table public."SpecialServices"
    owner to neos;

create index if not exists "IX_SpecialServices_IsDeleted"
    on public."SpecialServices" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_SpecialServices_MasterContractId"
    on public."SpecialServices" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_SpecialServices_SeriesId"
    on public."SpecialServices" ("SeriesId")
    where ("IsDeleted" = false);

create index if not exists "IX_SpecialServices_TypeId"
    on public."SpecialServices" ("TypeId")
    where ("IsDeleted" = false);

create table if not exists public."Taxes"
(
    "Id"             integer generated by default as identity
        constraint "PK_Taxes"
            primary key,
    "SeriesId"       integer                  not null
        constraint "FK_Taxes_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "Code"           varchar(32)              not null,
    "Value"          numeric(6, 3),
    "AirportId"      integer                  not null
        constraint "FK_Taxes_Airports_AirportId"
            references public."Airports"
            on delete cascade,
    "CurrencyId"     integer                  not null,
    "Direction"      integer                  not null
        constraint "CKE_Direction"
            check ("Direction" = ANY (ARRAY [0, 1])),
    "FlightDateFrom" date                     not null,
    "FlightDateTo"   date                     not null,
    "Included"       boolean                  not null,
    "Nation"         varchar(256)             not null,
    "Name"           varchar(256)             not null,
    "SaleDateFrom"   date                     not null,
    "TaxCarrier"     varchar(256)             not null,
    "Fp"             integer                  not null
        constraint "CKE_Fp"
            check ("Fp" = ANY (ARRAY [0, 1])),
    "Fbc"            varchar(256)             not null,
    "Ptc"            integer                  not null
        constraint "CKE_Ptc"
            check ("Ptc" = ANY (ARRAY [0, 1, 2])),
    "Percent"        integer,
    "TaxPoint"       integer                  not null
        constraint "CKE_TaxPoint"
            check ("TaxPoint" = ANY (ARRAY [0, 1])),
    "StopOver"       boolean                  not null,
    "CreatedAt"      timestamp with time zone not null,
    "CreatedBy"      integer                  not null,
    "UpdatedAt"      timestamp with time zone,
    "UpdatedBy"      integer,
    "DeletedAt"      timestamp with time zone,
    "DeletedBy"      integer,
    "IsDeleted"      boolean                  not null
);

comment on column public."Taxes"."Direction" is 'EnmTaxDirection values ( Inbound = 0, Outbound = 1 )';

comment on column public."Taxes"."Fp" is 'EnmTaxType values ( F = 0, P = 1 )';

comment on column public."Taxes"."Ptc" is 'EnmTaxPassengerTypeCode values ( ADT = 0, CHD = 1, INF = 2 )';

comment on column public."Taxes"."TaxPoint" is 'EnmTaxPoint values ( D = 0, A = 1 )';

alter table public."Taxes"
    owner to neos;

create index if not exists "IX_Taxes_AirportId"
    on public."Taxes" ("AirportId")
    where ("IsDeleted" = false);

create index if not exists "IX_Taxes_IsDeleted"
    on public."Taxes" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Taxes_SeriesId"
    on public."Taxes" ("SeriesId")
    where ("IsDeleted" = false);

create table if not exists public."Flights"
(
    "Id"                  integer generated by default as identity
        constraint "PK_Flights"
            primary key,
    "OriginDestinationId" integer                  not null
        constraint "FK_Flights_OriginDestinations_OriginDestinationId"
            references public."OriginDestinations"
            on delete cascade,
    "FlightIntegrationId" integer                  not null
        constraint "FK_Flights_FlightIntegrations_FlightIntegrationId"
            references public."FlightIntegrations"
            on delete cascade,
    "OperativeDay"        integer                  not null,
    "EconomySeats"        integer                  not null,
    "PremiumSeats"        integer                  not null,
    "FirstSeats"          integer                  not null,
    "ReleaseEconomySeats" integer                  not null,
    "ReleasePremiumSeats" integer                  not null,
    "ReleaseFirstSeats"   integer                  not null,
    "EconomyFareBasisId"  integer                  not null,
    "PremiumFareBasisId"  integer                  not null,
    "CreatedAt"           timestamp with time zone not null,
    "CreatedBy"           integer                  not null,
    "UpdatedAt"           timestamp with time zone,
    "UpdatedBy"           integer,
    "DeletedAt"           timestamp with time zone,
    "DeletedBy"           integer,
    "IsDeleted"           boolean                  not null
);

alter table public."Flights"
    owner to neos;

create index if not exists "IX_Flights_FlightIntegrationId"
    on public."Flights" ("FlightIntegrationId")
    where ("IsDeleted" = false);

create index if not exists "IX_Flights_IsDeleted"
    on public."Flights" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Flights_OriginDestinationId"
    on public."Flights" ("OriginDestinationId")
    where ("IsDeleted" = false);

create table if not exists public."SpecialServiceAircraftTypes"
(
    "SpecialServiceId" integer not null
        constraint "FK_SpecialServiceAircraftTypes_SpecialServices_SpecialServiceId"
            references public."SpecialServices"
            on delete cascade,
    "AircraftTypeId"   integer not null,
    constraint "PK_SpecialServiceAircraftTypes"
        primary key ("SpecialServiceId", "AircraftTypeId")
);

alter table public."SpecialServiceAircraftTypes"
    owner to neos;

create table if not exists public."FlightFares"
(
    "FareId"   integer not null
        constraint "FK_FlightFares_Fares_FareId"
            references public."Fares"
            on delete cascade,
    "FlightId" integer not null
        constraint "FK_FlightFares_Flights_FlightId"
            references public."Flights"
            on delete cascade,
    constraint "PK_FlightFares"
        primary key ("FareId", "FlightId")
);

alter table public."FlightFares"
    owner to neos;

create index if not exists "IX_FlightFares_FlightId"
    on public."FlightFares" ("FlightId");

create table if not exists public."Prices"
(
    "Id"                                     integer generated by default as identity
        constraint "PK_Prices"
            primary key,
    "FlightId"                               integer                  not null
        constraint "FK_Prices_Flights_FlightId"
            references public."Flights"
            on delete cascade,
    "ProSeat"                                numeric(10, 2)           not null,
    "SurchargePremium"                       numeric(10, 2)           not null,
    "SurchargeFirst"                         numeric(10, 2)           not null,
    "IntegrationCurrency"                    numeric(10, 2)           not null,
    "IntegrationFuel"                        numeric(10, 2)           not null,
    "IntegrationExtraLandingValue"           numeric(10, 2)           not null,
    "IntegrationExtraLandingCalculationType" integer                  not null
        constraint "CKE_IntegrationExtraLandingCalculationType"
            check ("IntegrationExtraLandingCalculationType" = ANY (ARRAY [0, 1, 2, 3])),
    "IntegrationCorsia"                      numeric(10, 2)           not null,
    "IntegrationSAF"                         numeric(10, 2)           not null,
    "IntegrationETS"                         numeric(10, 2)           not null,
    "IntegrationY1"                          numeric(10, 2)           not null,
    "IntegrationY2"                          numeric(10, 2)           not null,
    "IntegrationY3"                          numeric(10, 2)           not null,
    "IntegrationY4"                          numeric(10, 2)           not null,
    "IntegrationY5"                          numeric(10, 2)           not null,
    "IntegrationP1"                          numeric(10, 2)           not null,
    "IntegrationP2"                          numeric(10, 2)           not null,
    "IntegrationP3"                          numeric(10, 2)           not null,
    "IntegrationOtherValue"                  numeric(10, 2)           not null,
    "IntegrationOtherCalculationType"        integer                  not null
        constraint "CKE_IntegrationOtherCalculationType"
            check ("IntegrationOtherCalculationType" = ANY (ARRAY [0, 1, 2, 3])),
    "IntegrationOtherTwoValue"               numeric(10, 2)           not null,
    "IntegrationOtherTwoCalculationType"     integer                  not null
        constraint "CKE_IntegrationOtherTwoCalculationType"
            check ("IntegrationOtherTwoCalculationType" = ANY (ARRAY [0, 1, 2, 3])),
    "PenaltyFeeValue"                        numeric(10, 2)           not null,
    "PenaltyFeeUnitOfMeasureId"              integer                  not null
        constraint "FK_Prices_UnitOfMeasures_PenaltyFeeUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "PenaltyNoShowValue"                     numeric(10, 2)           not null,
    "PenaltyNoShowUnitOfMeasureId"           integer                  not null
        constraint "FK_Prices_UnitOfMeasures_PenaltyNoShowUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "CreatedAt"                              timestamp with time zone not null,
    "CreatedBy"                              integer                  not null,
    "UpdatedAt"                              timestamp with time zone,
    "UpdatedBy"                              integer,
    "DeletedAt"                              timestamp with time zone,
    "DeletedBy"                              integer,
    "IsDeleted"                              boolean                  not null
);

comment on column public."Prices"."IntegrationExtraLandingCalculationType" is 'EnmCalculationType values ( Guaranteed = 0, Sold = 1, ExtraAllotment = 2, Fixed = 3 )';

comment on column public."Prices"."IntegrationOtherCalculationType" is 'EnmCalculationType values ( Guaranteed = 0, Sold = 1, ExtraAllotment = 2, Fixed = 3 )';

comment on column public."Prices"."IntegrationOtherTwoCalculationType" is 'EnmCalculationType values ( Guaranteed = 0, Sold = 1, ExtraAllotment = 2, Fixed = 3 )';

alter table public."Prices"
    owner to neos;

create unique index if not exists "IX_Prices_FlightId"
    on public."Prices" ("FlightId")
    where ("IsDeleted" = false);

create index if not exists "IX_Prices_IsDeleted"
    on public."Prices" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Prices_PenaltyFeeUnitOfMeasureId"
    on public."Prices" ("PenaltyFeeUnitOfMeasureId")
    where ("IsDeleted" = false);

create index if not exists "IX_Prices_PenaltyNoShowUnitOfMeasureId"
    on public."Prices" ("PenaltyNoShowUnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."Releases"
(
    "Id"                     integer generated by default as identity
        constraint "PK_Releases"
            primary key,
    "FlightId"               integer                  not null
        constraint "FK_Releases_Flights_FlightId"
            references public."Flights"
            on delete cascade,
    "Day"                    integer                  not null,
    "PremiumSeats"           integer                  not null,
    "EconomySeats"           integer                  not null,
    "FirstSeats"             integer                  not null,
    "PenaltyValue"           numeric(10, 2)           not null,
    "PenaltyUnitOfMeasureId" integer                  not null
        constraint "FK_Releases_UnitOfMeasures_PenaltyUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "CreatedAt"              timestamp with time zone not null,
    "CreatedBy"              integer                  not null,
    "UpdatedAt"              timestamp with time zone,
    "UpdatedBy"              integer,
    "DeletedAt"              timestamp with time zone,
    "DeletedBy"              integer,
    "IsDeleted"              boolean                  not null
);

alter table public."Releases"
    owner to neos;

create index if not exists "IX_Releases_FlightId"
    on public."Releases" ("FlightId")
    where ("IsDeleted" = false);

create index if not exists "IX_Releases_IsDeleted"
    on public."Releases" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Releases_PenaltyUnitOfMeasureId"
    on public."Releases" ("PenaltyUnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."PriceAdditionalPrices"
(
    "PriceId"           integer not null
        constraint "FK_PriceAdditionalPrices_Prices_PriceId"
            references public."Prices"
            on delete cascade,
    "AdditionalPriceId" integer not null,
    constraint "PK_PriceAdditionalPrices"
        primary key ("PriceId", "AdditionalPriceId")
);

alter table public."PriceAdditionalPrices"
    owner to neos;

create table if not exists public."ParameterTypes"
(
    "Id"                         integer generated by default as identity
        constraint "PK_ParameterTypes"
            primary key,
    "Name"                       varchar(256)             not null,
    "Description"                varchar(512),
    "DataType"                   integer                  not null
        constraint "CKE_DataType"
            check ("DataType" = ANY (ARRAY [0, 1, 2, 3, 4, 5, 6])),
    "DefaultValueId"             integer,
    "DefaultIncidencePercentage" numeric,
    "UnitOfMeasureId"            integer
        constraint "FK_ParameterTypes_UnitOfMeasures_UnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "Applicability"              integer                  not null
        constraint "CKE_Applicability"
            check ("Applicability" = ANY (ARRAY [0, 1])),
    "Calculation"                varchar(512),
    "IsEditable"                 boolean                  not null,
    "CreatedAt"                  timestamp with time zone not null,
    "CreatedBy"                  integer                  not null,
    "UpdatedAt"                  timestamp with time zone,
    "UpdatedBy"                  integer,
    "DeletedAt"                  timestamp with time zone,
    "DeletedBy"                  integer,
    "IsDeleted"                  boolean                  not null
);

comment on column public."ParameterTypes"."DataType" is 'EnmParameterTypeDataType values ( Integer = 0, Decimal = 1, String = 2, Enum = 3, Boolean = 4, DateOnly = 5, DateTime = 6 )';

comment on column public."ParameterTypes"."Applicability" is 'EnmParameterTypeApplicability values ( MasterContract = 0, Series = 1 )';

alter table public."ParameterTypes"
    owner to neos;

create table if not exists public."Parameters"
(
    "Id"                   integer generated by default as identity
        constraint "PK_Parameters"
            primary key,
    "MasterContractId"     integer                  not null
        constraint "FK_Parameters_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "SeriesId"             integer
        constraint "FK_Parameters_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "TypeId"               integer                  not null
        constraint "FK_Parameters_ParameterTypes_TypeId"
            references public."ParameterTypes"
            on delete cascade,
    "Value"                varchar(512)             not null,
    "ValueUnitOfMeasureId" integer
        constraint "FK_Parameters_UnitOfMeasures_ValueUnitOfMeasureId"
            references public."UnitOfMeasures"
            on delete cascade,
    "IncidencePercentage"  numeric(6, 3),
    "ValidityFrom"         date,
    "ValidityTo"           date,
    "CreatedAt"            timestamp with time zone not null,
    "CreatedBy"            integer                  not null,
    "UpdatedAt"            timestamp with time zone,
    "UpdatedBy"            integer,
    "DeletedAt"            timestamp with time zone,
    "DeletedBy"            integer,
    "IsDeleted"            boolean                  not null
);

alter table public."Parameters"
    owner to neos;

create index if not exists "IX_Parameters_IsDeleted"
    on public."Parameters" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Parameters_MasterContractId"
    on public."Parameters" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_Parameters_SeriesId"
    on public."Parameters" ("SeriesId")
    where ("IsDeleted" = false);

create index if not exists "IX_Parameters_TypeId"
    on public."Parameters" ("TypeId")
    where ("IsDeleted" = false);

create index if not exists "IX_Parameters_ValueUnitOfMeasureId"
    on public."Parameters" ("ValueUnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."ParameterTypeAircraftTypes"
(
    "ParameterTypeId" integer not null
        constraint "FK_ParameterTypeAircraftTypes_ParameterTypes_ParameterTypeId"
            references public."ParameterTypes"
            on delete cascade,
    "AircraftTypeId"  integer not null,
    constraint "PK_ParameterTypeAircraftTypes"
        primary key ("ParameterTypeId", "AircraftTypeId")
);

alter table public."ParameterTypeAircraftTypes"
    owner to neos;

create index if not exists "IX_ParameterTypes_Applicability"
    on public."ParameterTypes" ("Applicability")
    where ("IsDeleted" = false);

create unique index if not exists "IX_ParameterTypes_DefaultValueId"
    on public."ParameterTypes" ("DefaultValueId")
    where ("IsDeleted" = false);

create index if not exists "IX_ParameterTypes_IsDeleted"
    on public."ParameterTypes" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_ParameterTypes_Name"
    on public."ParameterTypes" ("Name")
    where ("IsDeleted" = false);

create index if not exists "IX_ParameterTypes_UnitOfMeasureId"
    on public."ParameterTypes" ("UnitOfMeasureId")
    where ("IsDeleted" = false);

create table if not exists public."ParameterTypeValues"
(
    "Id"              integer generated by default as identity
        constraint "PK_ParameterTypeValues"
            primary key,
    "ParameterTypeId" integer                  not null
        constraint "FK_ParameterTypeValues_ParameterTypes_ParameterTypeId"
            references public."ParameterTypes"
            on delete cascade,
    "Value"           varchar(512)             not null,
    "Description"     varchar(256),
    "CreatedAt"       timestamp with time zone not null,
    "CreatedBy"       integer                  not null,
    "UpdatedAt"       timestamp with time zone,
    "UpdatedBy"       integer,
    "DeletedAt"       timestamp with time zone,
    "DeletedBy"       integer,
    "IsDeleted"       boolean                  not null
);

alter table public."ParameterTypeValues"
    owner to neos;

alter table public."ParameterTypes"
    add constraint "FK_ParameterTypes_ParameterTypeValues_DefaultValueId"
        foreign key ("DefaultValueId") references public."ParameterTypeValues"
            on delete cascade;

create index if not exists "IX_ParameterTypeValues_IsDeleted"
    on public."ParameterTypeValues" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_ParameterTypeValues_ParameterTypeId"
    on public."ParameterTypeValues" ("ParameterTypeId")
    where ("IsDeleted" = false);

