create table public."Taxes"
(
    "Id"             integer generated by default as identity
        constraint "PK_Taxes"
            primary key,
    "SeriesId"       integer                        not null
        constraint "FK_Taxes_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "Code"           varchar(32)                    not null,
    "Value"          numeric(10, 2),
    "AirportId"      integer                        not null
        constraint "FK_Taxes_Airports_AirportId"
            references public."Airports"
            on delete cascade,
    "CurrencyId"     integer                        not null
        constraint "FK_Taxes_UnitOfMeasures_CurrencyId"
            references public."UnitOfMeasures"
            on delete cascade,
    "Direction"      integer                        not null
        constraint "CKE_Direction"
            check ("Direction" = ANY (ARRAY [0, 1])),
    "FlightDateFrom" date                           not null,
    "FlightDateTo"   date                           not null,
    "Included"       boolean                        not null,
    "Nation"         varchar(256)                   not null,
    "Name"           varchar(256)                   not null,
    "SaleDateFrom"   date                           not null,
    "TaxCarrier"     varchar(256)                   not null,
    "Fp"             integer                        not null
        constraint "CKE_Fp"
            check ("Fp" = ANY (ARRAY [0, 1])),
    "Fbc"            varchar(256),
    "Ptc"            integer                        not null
        constraint "CKE_Ptc"
            check ("Ptc" = ANY (ARRAY [0, 1, 2, 3])),
    "Percent"        integer,
    "TaxPoint"       integer                        not null
        constraint "CKE_TaxPoint"
            check ("TaxPoint" = ANY (ARRAY [0, 1])),
    "StopOver"       boolean                        not null,
    "VatId"          integer
        constraint "FK_Taxes_Vats_VatId"
            references public."Vats"
            on delete cascade,
    "CreatedAt"      timestamp with time zone       not null,
    "CreatedBy"      integer                        not null,
    "UpdatedAt"      timestamp with time zone,
    "UpdatedBy"      integer,
    "DeletedAt"      timestamp with time zone,
    "DeletedBy"      integer,
    "IsDeleted"      boolean                        not null,
    "SaleDateTo"     date default '-infinity'::date not null
);

comment on column public."Taxes"."Direction" is 'EnmTaxDirection values ( Inbound = 0, Outbound = 1 )';

comment on column public."Taxes"."Fp" is 'EnmTaxType values ( F = 0, P = 1 )';

comment on column public."Taxes"."Ptc" is 'EnmTaxPassengerTypeCode values ( ADT = 0, CHD = 1, INF = 2, YTH = 3 )';

comment on column public."Taxes"."TaxPoint" is 'EnmTaxPoint values ( D = 0, A = 1 )';

alter table public."Taxes"
    owner to neos;

create index "IX_Taxes_AirportId"
    on public."Taxes" ("AirportId")
    where ("IsDeleted" = false);

create index "IX_Taxes_CurrencyId"
    on public."Taxes" ("CurrencyId")
    where ("IsDeleted" = false);

create index "IX_Taxes_IsDeleted"
    on public."Taxes" ("IsDeleted")
    where ("IsDeleted" = false);

create index "IX_Taxes_SeriesId"
    on public."Taxes" ("SeriesId")
    where ("IsDeleted" = false);

create index "IX_Taxes_VatId"
    on public."Taxes" ("VatId")
    where ("IsDeleted" = false);

