create table if not exists public."Proposals"
(
    "Id"               integer generated by default as identity
        constraint "PK_Proposals"
            primary key,
    "RequestId"        integer                  not null
        constraint "FK_Proposals_Requests_RequestId"
            references public."Requests"
            on delete cascade,
    "MasterContractId" integer                  not null
        constraint "FK_Proposals_MasterContracts_MasterContractId"
            references public."MasterContracts"
            on delete cascade,
    "CustomerId"       integer                  not null
        constraint "FK_Proposals_Companies_CustomerId"
            references public."Companies"
            on delete cascade,
    "OdFromId"         integer                  not null
        constraint "FK_Proposals_Airports_OdFromId"
            references public."Airports"
            on delete cascade,
    "OdToId"           integer                  not null
        constraint "FK_Proposals_Airports_OdToId"
            references public."Airports"
            on delete cascade,
    "DateFrom"         date                     not null,
    "DateTo"           date                     not null,
    "OperativeDay"     integer                  not null,
    "DestinationId"    integer                  not null,
    "AircraftTypeId"   integer,
    "SeasonId"         integer                  not null
        constraint "FK_Proposals_Seasons_SeasonId"
            references public."Seasons"
            on delete cascade,
    "Year"             smallint                 not null,
    "CurrencyId"       integer,
    "ContractTypeId"   integer
        constraint "FK_Proposals_ContractTypes_ContractTypeId"
            references public."ContractTypes",
    "RejectionReason"  text,
    "Status"           integer                  not null
        constraint "CKE_Status"
            check ("Status" = ANY (ARRAY [0, 1, 2, 3, 4])),
    "RoutingId"        integer,
    "GuaranteedSeatsP" integer                  not null,
    "GuaranteedSeatsY" integer                  not null,
    "GuaranteedSeatsF" integer                  not null,
    "ReleaseSeatsP"    integer                  not null,
    "ReleaseSeatsY"    integer                  not null,
    "ReleaseSeatsF"    integer                  not null,
    "Frequency"        integer                  not null
        constraint "CKE_Frequency"
            check ("Frequency" = ANY (ARRAY [0, 1, 2, 3])),
    "Notes"            text,
    "CreatedAt"        timestamp with time zone not null,
    "CreatedBy"        integer                  not null,
    "UpdatedAt"        timestamp with time zone,
    "UpdatedBy"        integer,
    "DeletedAt"        timestamp with time zone,
    "DeletedBy"        integer,
    "IsDeleted"        boolean                  not null
);

comment on column public."Proposals"."Status" is 'EnmProposalStatus values ( Sent = 0, Rejected = 1, InProgress = 2, Confirmed = 3, Modified = 4 )';

comment on column public."Proposals"."Frequency" is 'EnmOriginDestinationFrequency values ( Daily = 0, Weekly = 1, DD21 = 2, Monthly = 3 )';

alter table public."Proposals"
    owner to neos;

create index if not exists "IX_Proposals_ContractTypeId"
    on public."Proposals" ("ContractTypeId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_CustomerId"
    on public."Proposals" ("CustomerId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_IsDeleted"
    on public."Proposals" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_MasterContractId"
    on public."Proposals" ("MasterContractId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_OdFromId"
    on public."Proposals" ("OdFromId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_OdToId"
    on public."Proposals" ("OdToId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_RequestId"
    on public."Proposals" ("RequestId")
    where ("IsDeleted" = false);

create index if not exists "IX_Proposals_SeasonId"
    on public."Proposals" ("SeasonId")
    where ("IsDeleted" = false);

