create table if not exists public."FareSpecialServices"
(
    "Id"        integer generated by default as identity
        constraint "PK_FareSpecialServices"
            primary key,
    "FareId"    integer                  not null
        constraint "FK_FareSpecialServices_Fares_FareId"
            references public."Fares"
            on delete cascade,
    "Quantity"  integer                  not null,
    "TypeId"    integer                  not null
        constraint "FK_FareSpecialServices_SpecialTypes_TypeId"
            references public."SpecialTypes"
            on delete cascade,
    "CreatedAt" timestamp with time zone not null,
    "CreatedBy" integer                  not null,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" integer,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "IsDeleted" boolean                  not null
);

alter table public."FareSpecialServices"
    owner to neos;

create index if not exists "IX_FareSpecialServices_FareId"
    on public."FareSpecialServices" ("FareId")
    where ("IsDeleted" = false);

create index if not exists "IX_FareSpecialServices_IsDeleted"
    on public."FareSpecialServices" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_FareSpecialServices_TypeId"
    on public."FareSpecialServices" ("TypeId")
    where ("IsDeleted" = false);

