create table if not exists public."TaxVariationSeries"
(
    "Id"                    integer generated by default as identity
        constraint "PK_TaxVariationSeries"
            primary key,
    "TaxVariationRequestId" integer                  not null
        constraint "FK_TaxVariationSeries_TaxVariationRequests_TaxVariationRequest~"
            references public."TaxVariationRequests"
            on delete cascade,
    "SeriesId"              integer                  not null
        constraint "FK_TaxVariationSeries_Series_SeriesId"
            references public."Series"
            on delete cascade,
    "Status"                integer                  not null,
    "SupplierApproval"      boolean,
    "SupplierApprovalById"  integer
        constraint "FK_TaxVariationSeries_Users_SupplierApprovalById"
            references public."Users"
            on delete set null,
    "SupplierApprovalDate"  timestamp with time zone,
    "SupplierReason"        text,
    "BrokerApproval"        boolean,
    "BrokerApprovalById"    integer
        constraint "FK_TaxVariationSeries_Users_BrokerApprovalById"
            references public."Users"
            on delete set null,
    "BrokerApprovalDate"    timestamp with time zone,
    "BrokerReason"          text,
    "CustomerApproval"      boolean,
    "CustomerApprovalById"  integer
        constraint "FK_TaxVariationSeries_Users_CustomerApprovalById"
            references public."Users"
            on delete set null,
    "CustomerApprovalDate"  timestamp with time zone,
    "CustomerReason"        text,
    "CreatedAt"             timestamp with time zone not null,
    "CreatedBy"             integer                  not null,
    "UpdatedAt"             timestamp with time zone,
    "UpdatedBy"             integer,
    "DeletedAt"             timestamp with time zone,
    "DeletedBy"             integer,
    "IsDeleted"             boolean                  not null
);

comment on column public."TaxVariationSeries"."Status" is 'EnmTaxVariationSeriesStatus values ( PendingApproval = 0, Approved = 1, Rejected = 2, Applied = 3 )';

alter table public."TaxVariationSeries"
    owner to neos;

create index if not exists "IX_TaxVariationSeries_BrokerApproval"
    on public."TaxVariationSeries" ("BrokerApproval")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_BrokerApprovalById"
    on public."TaxVariationSeries" ("BrokerApprovalById");

create index if not exists "IX_TaxVariationSeries_CustomerApproval"
    on public."TaxVariationSeries" ("CustomerApproval")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_CustomerApprovalById"
    on public."TaxVariationSeries" ("CustomerApprovalById");

create index if not exists "IX_TaxVariationSeries_IsDeleted"
    on public."TaxVariationSeries" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_SeriesId"
    on public."TaxVariationSeries" ("SeriesId")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_Status"
    on public."TaxVariationSeries" ("Status")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_SupplierApproval"
    on public."TaxVariationSeries" ("SupplierApproval")
    where ("IsDeleted" = false);

create index if not exists "IX_TaxVariationSeries_SupplierApprovalById"
    on public."TaxVariationSeries" ("SupplierApprovalById");

create index if not exists "IX_TaxVariationSeries_TaxVariationRequestId"
    on public."TaxVariationSeries" ("TaxVariationRequestId")
    where ("IsDeleted" = false);

create unique index if not exists "IX_TaxVariationSeries_TaxVariationRequestId_SeriesId"
    on public."TaxVariationSeries" ("TaxVariationRequestId", "SeriesId")
    where ("IsDeleted" = false);

