create table if not exists public."Fares"
(
    "Id"                    integer generated by default as identity
        constraint "PK_Fares"
            primary key,
    "FlightId"              integer                  not null
        constraint "FK_Fares_Flights_FlightId"
            references public."Flights"
            on delete cascade,
    "FareBasisId"           integer                  not null,
    "GridClass"             integer                  not null
        constraint "CKE_GridClass"
            check ("GridClass" = ANY (ARRAY [0, 1, 2, 3, 4, 5])),
    "Value"                 numeric(6, 3)            not null,
    "MinPP"                 numeric(6, 3),
    "Min"                   numeric(6, 3),
    "Max"                   numeric(6, 3),
    "Default"               boolean,
    "ChdPercentageDiscount" integer,
    "InfPercentageDiscount" integer,
    "ValidityFrom"          date,
    "ValidityTo"            date,
    "DataOwningCarrierCode" integer                  not null
        constraint "CKE_DataOwningCarrierCode"
            check ("DataOwningCarrierCode" = 0),
    "TariffNumber"          integer                  not null
        constraint "CKE_TariffNumber"
            check ("TariffNumber" = ANY (ARRAY [0, 1, 2, 3, 4, 5, 6, 7])),
    "RuleNumber"            varchar(64),
    "FareType"              integer                  not null
        constraint "CKE_FareType"
            check ("FareType" = ANY (ARRAY [0, 1])),
    "OWRT"                  integer                  not null
        constraint "CKE_OWRT"
            check ("OWRT" = ANY (ARRAY [0, 1])),
    "RoutingNumber"         varchar(4),
    "FootNote"              varchar(512),
    "CreatedAt"             timestamp with time zone not null,
    "CreatedBy"             integer                  not null,
    "UpdatedAt"             timestamp with time zone,
    "UpdatedBy"             integer,
    "DeletedAt"             timestamp with time zone,
    "DeletedBy"             integer,
    "IsDeleted"             boolean                  not null
);

comment on column public."Fares"."GridClass" is 'EnmFareGridClass values ( S = 0, J = 1, X = 2, V = 3, Z = 4, I = 5 )';

comment on column public."Fares"."DataOwningCarrierCode" is 'EnmFareDataOwningCarrierCode values ( NO = 0 )';

comment on column public."Fares"."TariffNumber" is 'EnmFareTariffNumber values ( N023 = 0, N004 = 1, N022 = 2, N304 = 3, N021 = 4, N364 = 5, N027 = 6, N302 = 7 )';

comment on column public."Fares"."FareType" is 'EnmFareType values ( EU = 0, BU = 1 )';

comment on column public."Fares"."OWRT" is 'EnmFareOwrt values ( OneWay = 0, RoundTrip = 1 )';

alter table public."Fares"
    owner to neos;

create index if not exists "IX_Fares_FareBasisId"
    on public."Fares" ("FareBasisId")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_FlightId"
    on public."Fares" ("FlightId")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_IsDeleted"
    on public."Fares" ("IsDeleted")
    where ("IsDeleted" = false);

