create table if not exists public."Fares"
(
    "Id"                    integer generated by default as identity
        constraint "PK_Fares"
            primary key,
    "FareBasis"             varchar(256)             not null,
    "GridClass"             integer                  not null
        constraint "CKE_GridClass"
            check ("GridClass" = ANY (ARRAY [0, 1, 2, 3, 4, 5, 6])),
    "Value"                 numeric(6, 3)            not null,
    "ValidityFrom"          date                     not null,
    "ValidityTo"            date                     not null,
    "MinPassengers"         integer                  not null,
    "Min"                   integer,
    "Max"                   integer,
    "IsDefault"             boolean                  not null,
    "YthPercentageDiscount" integer                  not null,
    "ChdPercentageDiscount" integer                  not null,
    "InfPercentageDiscount" integer                  not null,
    "DataOwningCarrierCode" integer                  not null
        constraint "CKE_DataOwningCarrierCode"
            check ("DataOwningCarrierCode" = 0),
    "TariffNumber"          integer                  not null
        constraint "CKE_TariffNumber"
            check ("TariffNumber" = ANY (ARRAY [4, 21, 22, 23, 27, 302, 304, 364])),
    "RuleNumber"            varchar(64)              not null,
    "FareType"              integer                  not null
        constraint "CKE_FareType"
            check ("FareType" = ANY (ARRAY [0, 1])),
    "OWRT"                  integer                  not null
        constraint "CKE_OWRT"
            check ("OWRT" = ANY (ARRAY [1, 2])),
    "RoutingNumber"         integer                  not null,
    "FootNote"              text,
    "CreatedAt"             timestamp with time zone not null,
    "CreatedBy"             integer                  not null,
    "UpdatedAt"             timestamp with time zone,
    "UpdatedBy"             integer,
    "DeletedAt"             timestamp with time zone,
    "DeletedBy"             integer,
    "IsDeleted"             boolean                  not null
);

comment on column public."Fares"."GridClass" is 'EnmFareGridClass values ( A = 0, S = 1, J = 2, X = 3, V = 4, Z = 5, I = 6 )';

comment on column public."Fares"."DataOwningCarrierCode" is 'EnmFareDataOwningCarrierCode values ( NO = 0 )';

comment on column public."Fares"."TariffNumber" is 'EnmFareTariffNumber values ( N004 = 4, N021 = 21, N022 = 22, N023 = 23, N027 = 27, N302 = 302, N304 = 304, N364 = 364 )';

comment on column public."Fares"."FareType" is 'EnmFareType values ( EU = 0, WR = 1 )';

comment on column public."Fares"."OWRT" is 'EnmFareOwrt values ( OneWay = 1, RoundTrip = 2 )';

alter table public."Fares"
    owner to neos;

create index if not exists "IX_Fares_FareBasis"
    on public."Fares" ("FareBasis")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_IsDeleted"
    on public."Fares" ("IsDeleted")
    where ("IsDeleted" = false);

create index if not exists "IX_Fares_TariffNumber"
    on public."Fares" ("TariffNumber")
    where ("IsDeleted" = false);

